---
# Install apache and dependencies

- name: Install webserver software
  sudo: true
  apt: pkg={{ item }} state=latest update_cache=true
  ignore_errors: True
  with_items:
    - apache2
    - libapache2-mod-php5
    - libapache2-mod-passenger
    - libapache2-mod-wsgi

- name: Ensure apache2 is running
  service: name=apache2 state=started enabled=yes

- name: Enable apache2 modules
  sudo: true
  shell: "{{ item }}"
  with_items:
    - a2enmod rewrite
    - a2enmod ssl
    - a2enmod expires
    - a2enmod headers
    - /etc/init.d/apache2 restart
