---
#  Install generic development packages

- hosts: all
  tasks:
  - name: Install generic development software
    sudo: true
    package: name={{ item }} state=present
    with_items:
      - git
      - git-extras
      - ntp
      - tree
      - bc
      - curl
      - sl
      - zsh
      - mc
      - tmux
      - tig
      - xclip
      - filezilla
      - mpv
      - entr
      - clipit
      - meld
      - jq
    when: ansible_os_family == "Debian"

  - name: Install gems
    gem: name={{ item }} state=present
    with_items:
      - git-up
      - compass
      - tmuxinator

  - name: Install livereload
    sudo: true
    shell: pip install livereload
