---
#  Install PHP development packages

- hosts: all
  tasks:
  - name: Install PHP development software (Debian OS family)
    sudo: true
    package: name={{ item }} state=present
    with_items:
      - php-cli
      - php-codesniffer
      - phpunit
    when: ansible_os_family == "Debian"
