---
#  Install Python development packages

- hosts: all
  tasks:
  - name: Install Python development software (Debian OS family)
    sudo: true
    package: name={{ item }} state=present
    with_items:
      - python-pylibmc
      - python-pip
      - fabric
      - python-virtualenv
      - pylint
      - libmemcached-dev
      - libmysqlclient-dev
      - libmysqld-dev
      - libsqlite0-dev
      - libsqlite3-dev
      - python-dev
      - python3-dev
    when: ansible_os_family == "Debian"

  - name: Install Python development software (Redhat OS family)
    sudo: true
    package: name={{ item }} state=present
    with_items:
      - libxml2
      - libxml2-devel
      - libxslt
      - libxslt-devel
      - redhat-rpm-config
      - python-devel
      - python3-devel
      - memcached-devel
      - libmemcached-devel
      - gcc-c++
      - mysql-devel
      - sqlite-devel
    when: ansible_os_family == "RedHat"

  - name: Install livereload
    sudo: true
    shell: pip install livereload

  - name: Install fabric
    sudo: true
    shell: pip install fabric

  - name: Install Django debug server
    sudo: true
    shell: pip install Werkzeug
