---
- hosts: all
  sudo: yes
  roles:
    - franklinkim.ssh
  vars:
    ssh_port:
      - 2022
    ssh_permit_root_login: 'yes'
    ssh_pubkey_authentication: 'yes'
    ssh_password_authentication: 'yes'
    ssh_known_hosts:
      - github.com
      - bitbucket.org
