---
# Install commom webserver software

- name: Install webserver software
  sudo: true
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - git
    - apache2
    - nodejs
    - python-dev
    - python-virtualenv
- name: ensure apache2 is running
  service: name=apache2 state=started enabled=yes
