---
# Install commom webserver software

- name: Install webserver software
  sudo: true
  apt: pkg={{ item }} state=latest update_cache=true
  ignore_errors: True
  with_items:
    - git
    - mercurial
    - nodejs
    - npm
    - python-dev
    - python-virtualenv
    - build-essential
    - sloccount
    - php5
    - php5-cli
    - php5-mysql
    - php5-gd
    - php5-pgsql
    - php5-readline
    - php5-sqlite
    - php5-imagick
    - php5-memcache
    - php5-memcached
    - php5-redis
    - php5-curl
    - php-zip
    - mysql-server
    - locales-all
    - libxml2-dev
    - libxslt1-dev

- name: Install Python PIL support
  sudo: true
  apt: pkg={{ item }} state=latest update_cache=true
  ignore_errors: True
  with_items:
    - libjpeg8
    - libjpeg8-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-imaging

- name: Complete PIL support setup
  sudo: true
  shell: "{{ item }}"
  with_items:
    - ln -f -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib
    - ln -f -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib
    - ln -f -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib
