#  Install development software
---

- name: Install development software
  sudo: true
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - elinks
    - git
    - htop
    - iftop
    - iotop
    - nmap
    - ntp
    - tree
    - sl
    - whois
    - bc
    - vim
    - openssh-server
    - zsh
    - mc
    - tmux
    - ruby
    - ruby-dev
    - python-software-properties
    - software-properties-common
    - postfix
    - silversearcher-ag
    - vim-nox
    - tig
    - xclip
    - git-extras
    - filezilla
    - mpv
    - entr
    - clipit
    - python-pylibmc
    - libmemcached-dev
    - redis-tools
    - mysql-client
    - libmysqlclient-dev
    - python-pip
    - meld
    - libsqlite3-dev
    - g++
    - nautilus-dropbox

- name: Install git-up
  sudo: true
  shell: gem install git-up

- name: Install compass
  sudo: true
  shell: gem install compass

- name: Install tmuxinator
  sudo: true
  shell: gem install tmuxinator

- name: Install livereload
  sudo: true
  shell: pip install livereload


# TODO: phpunit, but not from apt-get but from some source
# TODO: sud pip install fabric
# TODO: check ytec is-my-setup for more packages
# TODO: setup psr2: sudo phpcs --config-set default_standard PSR2
# TODO: Docker from https://docs.docker.com/engine/installation/linux/ubuntulinux/
# TODO: Docker compose from https://docs.docker.com/compose/install/
