#  Install development software
---
- name: Install development software
  sudo: true
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - elinks
    - git
    - htop
    - iftop
    - iotop
    - nmap
    - ntp
    - tree
    - sl
    - whois
    - bc
    - vim
    - openssh-server
    - zsh
    - mc
    - tmux
    - ruby
    - ruby-dev
    - python-software-properties
    - software-properties-common
    - postfix
    - silversearcher-ag
    - vim-nox
    - memcached
    - tig
    - xclip
    - git-extras
    - filezilla
    - deluged
    - deluge-web
    - mpv
    - entr
    - clipit
    - python-pylibmc
    - libmemcached-dev


# TODO: mailtrap configuration
# TODO: neovim installation with ppa
# TODO: tmuxinator installation with ppa
# TODO: gem install git-up
# TODO: gem install compass
# TODO: enable php short tags
# TODO: fix node with: sudo update-alternatives --install /usr/bin/node node /usr/bin/nodejs 99
# TODO: phpunit, but not from apt-get but from some source
# TODO: sud pip install fabric
# TODO: check ytec is-my-setup for more packages
# TODO: setup psr2: sudo phpcs --config-set default_standard PSR2
