---
#  Install JavaScript development packages

- hosts: all
  tasks:
  - name: Install JavaScript development software (Debian OS family)
    apt:
      update_cache: yes
      pkg:
        - npm
    when: ansible_os_family == "Debian"

  - name: Upgrade NPM with NPM
    shell: npm install npm -g

  - name: Install NVM
    shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
