---
# Install Nagios NRPE server which will allow Nagios Main Server to connect and get data from
#
# You should create following files yourself:
#
#   - private/nagios-nrpe/nrpe.cfg
#     Main file with rules for NRPE server who can access information.
#
#   - private/nagios-nrpe/nrpe_local.cfg
#     List of commands Main Nagios Server can access / use.
#
#   - private/nagios-nrpe/plugins/*
#     List of Nagios NRPE plugins that could be used by previous config file.

- hosts: all
  tasks:
    - name: Install Nagios NRPE reporting library
      apt:
        name: nagios-nrpe-server
        state: present

    - name: Install config file allowing to connect Main Nagios Server
      copy: src=private/nagios-nrpe/nrpe.cfg dest=/etc/nagios/nrpe.cfg

    - name: Setup commands list Main Nagios server allowed to access
      copy: src=private/nagios-nrpe/nrpe_local.cfg dest=/etc/nagios/nrpe_local.cfg

    - name: Install NRPE plugins
      copy:
        src: private/nagios-nrpe/plugins/
        dest: /usr/lib/nagios/plugins/
        mode: '0755'

    - name: Apply new NRPE configurations
      service:
        name: nagios-nrpe-server
        state: restarted
