---
#  Install commom software
- name: Install common software
  sudo: true
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - elinks
    - git
    - htop
    - iftop
    - iotop
    - nmap
    - ntp
    - tree
    - sl
    - whois
    - bc
